# Generated by Django 5.1 on 2024-08-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkentity',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
