# Generated by Django 5.1 on 2024-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_networkentity_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkentity',
            name='supplier_type',
            field=models.IntegerField(choices=[(0, 'завод'), (1, 'розничная сеть'), (2, 'индивидуальный предприниматель')], default=0, verbose_name='тип поставщика'),
        ),
        migrations.AlterField(
            model_name='networkentity',
            name='level',
            field=models.PositiveIntegerField(editable=False, verbose_name='уровень иерархии'),
        ),
    ]
