# Generated by Django 5.1 on 2024-08-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_networkentity_supplier_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
