# Generated by Django 5.1 on 2024-08-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название продукта')),
                ('model', models.TextField(blank=True, null=True, verbose_name='описание продукта')),
                ('release_date', models.DateField(verbose_name='дата выхода на рынок')),
                ('network_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='network.networkentity')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
